### ISSUE TITLE
Accessing Revit system families parameter

### ISSUE THREAD

**Issue by sshweta22** [jeremytammik/jmonodb#1]
Hi Jeremy,

I am developing a plugin in Revit 2017 using C# in which I am trying to access parameters of certain system family.
For example, I am able to access built-in parameter "Width"  of system family "Walls". Similar approach does not work for Structural foundations , Floors etc.
For Structural Foundation and floors plugin needs to access thickness (built in parameter), but I get some strange errors.

I tried searching in your Revit blogs , but haven't got any specific topic related to my query.

Can you please tell me how to resolve this issue.?

P.S: I work as software developer, and major development area is asp.net mvc web portal.
But I am new to Revit- Development.

Thanks & Regards,
Sweta

**Comment by jeremytammik** [comment]
This question is covered by the getting started material pointed to at http://thebuildingcoder.typepad.com/blog/about-the-author.html#2.

Work through that first. This basic information includes the answer to your question.

It also includes installing RevitLookup, which enables you to explore the Revit database contents and element properties interactively. That will also answer your question. 

Finally, if any questions crop up that are note covered by the getting started material, the best place to ask and discuss those with your peers is in the Revit API discussion forum at http://forums.autodesk.com/t5/revit-api/bd-p/160.
