### ISSUE TITLE
Revit API Coordinates for Beam and Columns

### ISSUE THREAD

**Issue by sshweta22** [jeremytammik/jmonodb#2]
Hi,
 
I am trying to get coordinates for structural beams and columns.

I have created a dynamo file where-in I am using Geometry.Transform node to get desired coordinates.

The same I am trying in c#, but unable to do so.

Please advise how to proceed for same.

![coordinate](https://user-images.githubusercontent.com/18412171/35603810-1837c9f0-0665-11e8-91d0-4e2064c66daa.JPG)
![revit](https://user-images.githubusercontent.com/18412171/35603811-187596c2-0665-11e8-80aa-9615f9ac0f2a.JPG)

**Comment by jeremytammik** [comment]
totally off topic
